spring.application.name: foodpick

# Database Configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodpick?serverTimezone=Asia/Seoul
    username: root
    password: 1234  # MySQL 설정한 비밀번호

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

# Server Configuration
server.port: 8080

# JWT Configuration
jwt:
  secret: "pKS,tv..*Y4Mx`g:Vyd&GSiFb-P7dUoHtF#`3^Q,dGqTX,kr4z6.9p)j:E:Yw<j"
  expiration: 86400000